apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: rastislavpasek/ambulance-ufe
  newName: rastislavpasek/ambulance-ufe # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
  newTag: main.20260414.0818 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
- name: rastislavpasek/ambulance-wl-webapi
  newName: rastislavpasek/ambulance-wl-webapi # {"$imagepolicy":  "wac-hospital:ambulance-webapi:name"}
  newTag: main.20260331.1110 # {"$imagepolicy": "wac-hospital:ambulance-webapi:tag"}
